import { prisma } from "./config/prisma.js";
import { Prisma } from "./generated/client/client.js";

const seedDB = async () => {
  try {
    await prisma.product.deleteMany({});
    console.log("Cleared existing products....");

    const products: Prisma.ProductCreateManyInput[] = [
      // ─── SHIRTS (1–18) ───────────────────────────────────────────────
      {
        name: "Oxford Button-Down Shirt",
        description:
          "Classic Oxford weave button-down collar shirt crafted from premium 100% cotton. Timeless style suitable for office or weekend wear.",
        price: 1499,
        originalPrice: 1999,
        image:
          "https://images.unsplash.com/photo-1598033129183-c4f50c736c10?w=500&q=80",
        category: "shirts",
        unit: "piece",
        stock: 85,
        isOrganic: false,
        rating: 4.6,
        reviewCount: 142,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["White", "Blue", "Pink"],
        fits: ["Regular Fit"],
        patterns: ["Plain"],
        occasions: ["Formal", "Office Wear"],
        brands: ["Van Heusen"],
        materials: ["Cotton"],
        collarTypes: ["Button Down Collar"],
        sleeveLengths: ["Full Sleeve"],
        tags: ["Formal", "New", "Plain"],
      },
      {
        name: "Slim Fit Linen Shirt",
        description:
          "Breathable pure linen shirt with a modern slim fit. Perfect for summer outings and vacation wear.",
        price: 1799,
        originalPrice: 2299,
        image:
          "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&q=80",
        category: "shirts",
        unit: "piece",
        stock: 60,
        isOrganic: false,
        rating: 4.4,
        reviewCount: 98,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Beige", "Olive", "White"],
        fits: ["Slim Fit"],
        patterns: ["Plain"],
        occasions: ["Casual", "Vacation Wear"],
        brands: ["Allen Solly"],
        materials: ["Linen"],
        collarTypes: ["Spread Collar"],
        sleeveLengths: ["Full Sleeve"],
        tags: ["Linen", "Slim", "New"],
      },
      {
        name: "Check Pattern Formal Shirt",
        description:
          "Sophisticated check pattern shirt in wrinkle-resistant cotton blend. Ideal for boardroom meetings and formal gatherings.",
        price: 1299,
        originalPrice: 1799,
        image:
          "https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?w=500&q=80",
        category: "shirts",
        unit: "piece",
        stock: 120,
        isOrganic: false,
        rating: 4.3,
        reviewCount: 76,
        sizes: ["M", "L", "XL", "XXL"],
        colors: ["Blue", "Grey"],
        fits: ["Regular Fit"],
        patterns: ["Checks"],
        occasions: ["Formal", "Office Wear"],
        brands: ["Peter England"],
        materials: ["Cotton", "Polyester"],
        collarTypes: ["Classic Collar"],
        sleeveLengths: ["Full Sleeve"],
        tags: ["Checks", "Formal"],
      },
      {
        name: "Cuban Collar Resort Shirt",
        description:
          "Relaxed-fit tropical print Cuban collar shirt. Made from lightweight viscose for ultimate comfort in warm weather.",
        price: 999,
        originalPrice: 1499,
        image:
          "https://images.unsplash.com/photo-1617137968427-85924c800a22?w=500&q=80",
        category: "shirts",
        unit: "piece",
        stock: 45,
        isOrganic: false,
        rating: 4.7,
        reviewCount: 203,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Navy", "Green", "Black"],
        fits: ["Relaxed Fit"],
        patterns: ["Printed"],
        occasions: ["Casual", "Vacation Wear"],
        brands: ["Jack & Jones"],
        materials: ["Viscose"],
        collarTypes: ["Cuban Collar"],
        sleeveLengths: ["Half Sleeve"],
        tags: ["Relaxed", "Prints", "Half Sleeve"],
      },
      {
        name: "Striped Bengal Formal Shirt",
        description:
          "Elegant Bengal stripe shirt with a classic collar. Crafted from premium cotton for a crisp, professional look.",
        price: 1599,
        originalPrice: 1999,
        image:
          "https://images.unsplash.com/photo-1563630423918-b58f07336ac9?w=500&q=80",
        category: "shirts",
        unit: "piece",
        stock: 90,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 115,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["White", "Blue"],
        fits: ["Slim Fit"],
        patterns: ["Stripes"],
        occasions: ["Formal", "Office Wear"],
        brands: ["Louis Philippe"],
        materials: ["Cotton"],
        collarTypes: ["Classic Collar"],
        sleeveLengths: ["Full Sleeve"],
        tags: ["Stripes", "Slim", "Formal"],
      },
      {
        name: "Mandarin Collar Casual Shirt",
        description:
          "Contemporary mandarin collar shirt in soft cotton. A versatile piece that transitions from day to evening effortlessly.",
        price: 1199,
        originalPrice: 1599,
        image:
          "https://images.unsplash.com/photo-1621072156002-e2fccdc0b176?w=500&q=80",
        category: "shirts",
        unit: "piece",
        stock: 70,
        isOrganic: false,
        rating: 4.2,
        reviewCount: 64,
        sizes: ["M", "L", "XL"],
        colors: ["Black", "White", "Maroon"],
        fits: ["Slim Fit"],
        patterns: ["Plain"],
        occasions: ["Casual", "Festive Wear"],
        brands: ["Mufti"],
        materials: ["Cotton"],
        collarTypes: ["Mandarin Collar"],
        sleeveLengths: ["Full Sleeve"],
        tags: ["Festive Wear", "Slim"],
      },
      {
        name: "Oversized Graphic Print Tee",
        description:
          "Street-style oversized T-shirt with bold graphic print. Made from heavyweight 220 GSM cotton for a premium drape.",
        price: 799,
        originalPrice: 1199,
        image:
          "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500&q=80",
        category: "shirts",
        unit: "piece",
        stock: 200,
        isOrganic: false,
        rating: 4.8,
        reviewCount: 312,
        sizes: ["M", "L", "XL", "XXL", "3XL"],
        colors: ["Black", "White", "Grey"],
        fits: ["Oversized Fit"],
        patterns: ["Graphic Print"],
        occasions: ["Casual"],
        brands: ["Jack & Jones"],
        materials: ["Cotton"],
        collarTypes: ["Round Neck"],
        sleeveLengths: ["Half Sleeve"],
        tags: ["Boxy", "Prints", "New"],
      },
      {
        name: "Polo Collar Classic Tee",
        description:
          "Iconic polo collar T-shirt in breathable pique cotton. Perfect for a smart-casual look on weekends.",
        price: 899,
        originalPrice: 1299,
        image:
          "https://images.unsplash.com/photo-1625910513413-5fc42c05aeaa?w=500&q=80",
        category: "shirts",
        unit: "piece",
        stock: 150,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 178,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Navy", "White", "Green", "Red"],
        fits: ["Regular Fit"],
        patterns: ["Plain"],
        occasions: ["Casual"],
        brands: ["U.S. Polo Assn."],
        materials: ["Cotton"],
        collarTypes: ["Polo Collar"],
        sleeveLengths: ["Half Sleeve"],
        tags: ["Core Lab", "Plain"],
      },
      {
        name: "Floral Print Half Sleeve Shirt",
        description:
          "Eye-catching floral print shirt perfect for brunches and parties. Crafted from smooth rayon fabric that flows beautifully.",
        price: 1099,
        originalPrice: 1499,
        image:
          "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500&q=80",
        category: "shirts",
        unit: "piece",
        stock: 55,
        isOrganic: false,
        rating: 4.1,
        reviewCount: 52,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Blue", "Pink", "Multi"],
        fits: ["Regular Fit"],
        patterns: ["Floral"],
        occasions: ["Casual", "Party Wear"],
        brands: ["Jack & Jones"],
        materials: ["Rayon"],
        collarTypes: ["Spread Collar"],
        sleeveLengths: ["Half Sleeve"],
        tags: ["Prints", "Half Sleeve"],
      },
      {
        name: "Denim Western Shirt",
        description:
          "Rugged denim shirt with a vintage western vibe. Double chest pockets and snap button closure for authentic style.",
        price: 1899,
        originalPrice: 2499,
        image:
          "https://images.unsplash.com/photo-1588359348347-9bc6cbbb689e?w=500&q=80",
        category: "shirts",
        unit: "piece",
        stock: 40,
        isOrganic: false,
        rating: 4.6,
        reviewCount: 87,
        sizes: ["M", "L", "XL", "XXL"],
        colors: ["Blue", "Black"],
        fits: ["Regular Fit"],
        patterns: ["Plain"],
        occasions: ["Casual"],
        brands: ["Levi's"],
        materials: ["Cotton"],
        collarTypes: ["Spread Collar"],
        sleeveLengths: ["Full Sleeve"],
        tags: ["Denim", "Relaxed"],
      },
      {
        name: "Embroidered Festive Kurta Shirt",
        description:
          "Elegantly embroidered short kurta shirt for festive occasions. Made from premium cotton with a comfortable regular fit.",
        price: 2199,
        originalPrice: 2999,
        image:
          "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&q=80",
        category: "shirts",
        unit: "piece",
        stock: 30,
        isOrganic: false,
        rating: 4.7,
        reviewCount: 156,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["White", "Cream", "Lavender"],
        fits: ["Regular Kurta Fit"],
        patterns: ["Embroidered"],
        occasions: ["Festive Wear"],
        brands: ["Allen Solly"],
        materials: ["Cotton"],
        collarTypes: ["Mandarin Collar"],
        sleeveLengths: ["Full Sleeve"],
        tags: ["Festive Wear", "Luxe"],
      },
      {
        name: "Textured Knit Polo",
        description:
          "Premium textured knit polo with ribbed collar and cuffs. Perfect for layering or wearing solo.",
        price: 1399,
        originalPrice: 1799,
        image:
          "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=500&q=80",
        category: "shirts",
        unit: "piece",
        stock: 95,
        isOrganic: false,
        rating: 4.4,
        reviewCount: 91,
        sizes: ["M", "L", "XL"],
        colors: ["Grey", "Navy", "Brown"],
        fits: ["Slim Fit"],
        patterns: ["Textured"],
        occasions: ["Casual", "Office Wear"],
        brands: ["Tommy Hilfiger"],
        materials: ["Cotton", "Polyester"],
        collarTypes: ["Polo Collar"],
        sleeveLengths: ["Half Sleeve"],
        tags: ["Core Lab", "Slim"],
      },
      {
        name: "Box Fit Washed Cotton Shirt",
        description:
          "Trendy box fit shirt in garment-washed cotton. Relaxed drop shoulders give a contemporary streetwear edge.",
        price: 1099,
        originalPrice: 1599,
        image:
          "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=500&q=80",
        category: "shirts",
        unit: "piece",
        stock: 65,
        isOrganic: false,
        rating: 4.3,
        reviewCount: 44,
        sizes: ["M", "L", "XL", "XXL"],
        colors: ["Olive", "Khaki", "Beige"],
        fits: ["Box Fit"],
        patterns: ["Plain"],
        occasions: ["Casual"],
        brands: ["Mufti"],
        materials: ["Cotton"],
        collarTypes: ["Spread Collar"],
        sleeveLengths: ["Half Sleeve"],
        tags: ["Boxy", "Relaxed", "New"],
      },
      {
        name: "Colourblocked Casual Shirt",
        description:
          "Bold colour-blocked shirt with contrasting panels. A statement piece that pairs perfectly with chinos or jeans.",
        price: 1299,
        originalPrice: 1699,
        image:
          "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500&q=80",
        category: "shirts",
        unit: "piece",
        stock: 50,
        isOrganic: false,
        rating: 4.0,
        reviewCount: 33,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Multi", "Blue", "Green"],
        fits: ["Regular Fit"],
        patterns: ["Colourblocked"],
        occasions: ["Casual", "Party Wear"],
        brands: ["Wrangler"],
        materials: ["Cotton", "Polyester"],
        collarTypes: ["Spread Collar"],
        sleeveLengths: ["Full Sleeve"],
        tags: ["Prints", "New"],
      },
      {
        name: "Hooded Full Sleeve Henley",
        description:
          "Casual hooded henley with a layered look. Soft cotton-modal blend provides all-day comfort.",
        price: 999,
        originalPrice: 1499,
        image:
          "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=500&q=80",
        category: "shirts",
        unit: "piece",
        stock: 75,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 120,
        sizes: ["M", "L", "XL", "XXL"],
        colors: ["Grey", "Black", "Navy"],
        fits: ["Regular Fit"],
        patterns: ["Plain"],
        occasions: ["Casual"],
        brands: ["Mufti"],
        materials: ["Cotton", "Modal"],
        collarTypes: ["Hooded Collar"],
        sleeveLengths: ["Full Sleeve"],
        tags: ["Relaxed", "New"],
      },
      {
        name: "Ombre Dip-Dye Casual Shirt",
        description:
          "Trendy ombre dip-dye effect on lightweight cotton. A conversation-starter that blends artistry with comfort.",
        price: 1599,
        originalPrice: 2199,
        image:
          "https://images.unsplash.com/photo-1627225924765-552d49cf47ad?w=500&q=80",
        category: "shirts",
        unit: "piece",
        stock: 35,
        isOrganic: false,
        rating: 4.6,
        reviewCount: 67,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Blue", "Pink", "Peach"],
        fits: ["Slim Fit"],
        patterns: ["Ombre"],
        occasions: ["Casual", "Party Wear"],
        brands: ["Jack & Jones"],
        materials: ["Cotton"],
        collarTypes: ["Spread Collar"],
        sleeveLengths: ["Full Sleeve"],
        tags: ["Prints", "Luxe"],
      },
      {
        name: "Plus Size Relaxed Cotton Shirt",
        description:
          "Comfortable relaxed-fit shirt designed for plus sizes. Breathable cotton with generous proportions for effortless style.",
        price: 1299,
        originalPrice: 1699,
        image:
          "https://images.unsplash.com/photo-1564859228273-274232fdb516?w=500&q=80",
        category: "shirts",
        unit: "piece",
        stock: 40,
        isOrganic: false,
        rating: 4.3,
        reviewCount: 55,
        sizes: ["XXL", "3XL", "4XL", "5XL", "6XL"],
        colors: ["White", "Blue", "Black", "Grey"],
        fits: ["Relaxed Fit"],
        patterns: ["Plain"],
        occasions: ["Casual", "Office Wear"],
        brands: ["Peter England"],
        materials: ["Cotton"],
        collarTypes: ["Spread Collar"],
        sleeveLengths: ["Full Sleeve"],
        tags: ["Plus Size", "Relaxed"],
      },
      {
        name: "Jacquard Weave Party Shirt",
        description:
          "Premium jacquard weave shirt with subtle self-pattern. A luxurious choice for evening events and celebrations.",
        price: 2499,
        originalPrice: 3299,
        image:
          "https://images.unsplash.com/photo-1603252109303-2751441dd157?w=500&q=80",
        category: "shirts",
        unit: "piece",
        stock: 25,
        isOrganic: false,
        rating: 4.8,
        reviewCount: 189,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Maroon", "Navy"],
        fits: ["Slim Fit"],
        patterns: ["Jacquard"],
        occasions: ["Party Wear", "Festive Wear"],
        brands: ["Louis Philippe"],
        materials: ["Polyester", "Viscose"],
        collarTypes: ["Classic Collar"],
        sleeveLengths: ["Full Sleeve"],
        tags: ["Luxe", "Festive Wear"],
      },

      // ─── JEANS (19–35) ───────────────────────────────────────────────
      {
        name: "Classic Slim Fit Dark Wash Jeans",
        description:
          "Timeless slim-fit jeans in a rich dark indigo wash. Four-way stretch denim for all-day comfort and a clean silhouette.",
        price: 1999,
        originalPrice: 2799,
        image:
          "https://images.unsplash.com/photo-1542272604-787c3835535d?w=500&q=80",
        category: "jeans",
        unit: "piece",
        stock: 110,
        isOrganic: false,
        rating: 4.7,
        reviewCount: 265,
        sizes: ["28", "30", "32", "34", "36", "38"],
        colors: ["Dark Blue"],
        fits: ["Slim Fit"],
        washes: ["Dark Wash"],
        patterns: ["Clean Look"],
        rises: ["Mid Rise"],
        stretches: ["Stretchable"],
        lengths: ["Full Length"],
        closureTypes: ["Zip Fly"],
        occasions: ["Casual", "Smart Casual"],
        brands: ["Levi's"],
        materials: ["Stretch Denim"],
        tags: ["Slim", "Classic", "New"],
      },
      {
        name: "Relaxed Fit Light Wash Jeans",
        description:
          "Easy-going relaxed fit jeans with a vintage light wash. Wide leg opening for a retro-inspired casual look.",
        price: 1799,
        originalPrice: 2499,
        image:
          "https://images.unsplash.com/photo-1604176354204-9268737828e4?w=500&q=80",
        category: "jeans",
        unit: "piece",
        stock: 80,
        isOrganic: false,
        rating: 4.4,
        reviewCount: 134,
        sizes: ["30", "32", "34", "36", "38", "40"],
        colors: ["Light Blue"],
        fits: ["Relaxed Fit"],
        washes: ["Light Wash"],
        patterns: ["Faded"],
        rises: ["Mid Rise"],
        stretches: ["Non-Stretchable"],
        lengths: ["Full Length"],
        closureTypes: ["Zip Fly"],
        occasions: ["Casual"],
        brands: ["Wrangler"],
        materials: ["100% Cotton"],
        tags: ["Relaxed", "Washed", "Denim"],
      },
      {
        name: "Skinny Fit Black Jeans",
        description:
          "Ultra-slim black jeans with a modern tapered leg. Superstretch denim hugs the body while allowing freedom of movement.",
        price: 1699,
        originalPrice: 2299,
        image:
          "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500&q=80",
        category: "jeans",
        unit: "piece",
        stock: 95,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 198,
        sizes: ["28", "30", "32", "34", "36"],
        colors: ["Black"],
        fits: ["Skinny Fit"],
        washes: ["Dark Wash"],
        patterns: ["Plain"],
        rises: ["Low Rise"],
        stretches: ["Stretchable"],
        lengths: ["Full Length"],
        closureTypes: ["Zip Fly"],
        occasions: ["Casual", "Party Wear"],
        brands: ["Pepe Jeans"],
        materials: ["Stretch Denim"],
        tags: ["Slim", "Stretchable", "New"],
      },
      {
        name: "Straight Fit Stone Wash Jeans",
        description:
          "Classic straight-fit jeans with authentic stone wash treatment. Medium-weight cotton denim built to last.",
        price: 1599,
        originalPrice: 2199,
        image:
          "https://images.unsplash.com/photo-1582552938357-32b906df40cb?w=500&q=80",
        category: "jeans",
        unit: "piece",
        stock: 70,
        isOrganic: false,
        rating: 4.3,
        reviewCount: 89,
        sizes: ["30", "32", "34", "36", "38"],
        colors: ["Blue"],
        fits: ["Straight Fit"],
        washes: ["Stone Wash"],
        patterns: ["Washed"],
        rises: ["Mid Rise"],
        stretches: ["Non-Stretchable"],
        lengths: ["Full Length"],
        closureTypes: ["Zip Fly"],
        occasions: ["Casual"],
        brands: ["Lee"],
        materials: ["100% Cotton"],
        tags: ["Classic", "Stone Wash", "Denim"],
      },
      {
        name: "Ripped Distressed Slim Jeans",
        description:
          "Edgy ripped jeans with authentic distress detail at the knees. Slim fit with stretch for a comfortable, street-ready style.",
        price: 2199,
        originalPrice: 2999,
        image:
          "https://images.unsplash.com/photo-1475178626620-a4d074967571?w=500&q=80",
        category: "jeans",
        unit: "piece",
        stock: 55,
        isOrganic: false,
        rating: 4.6,
        reviewCount: 221,
        sizes: ["28", "30", "32", "34", "36"],
        colors: ["Blue", "Grey"],
        fits: ["Slim Fit"],
        washes: ["Medium Wash"],
        patterns: ["Ripped"],
        rises: ["Mid Rise"],
        stretches: ["Stretchable"],
        lengths: ["Full Length"],
        closureTypes: ["Zip Fly"],
        occasions: ["Casual", "Streetwear"],
        brands: ["Spykar"],
        materials: ["Stretch Denim"],
        tags: ["Streetwear", "Denim", "New"],
      },
      {
        name: "Bootcut Medium Wash Jeans",
        description:
          "Retro bootcut jeans with a medium indigo wash. Slight flare from knee down pairs perfectly with boots.",
        price: 1899,
        originalPrice: 2599,
        image:
          "https://images.unsplash.com/photo-1605518216938-7c31b7b14ad0?w=500&q=80",
        category: "jeans",
        unit: "piece",
        stock: 40,
        isOrganic: false,
        rating: 4.2,
        reviewCount: 56,
        sizes: ["30", "32", "34", "36", "38"],
        colors: ["Blue"],
        fits: ["Bootcut"],
        washes: ["Medium Wash"],
        patterns: ["Clean Look"],
        rises: ["Mid Rise"],
        stretches: ["Stretchable"],
        lengths: ["Full Length"],
        closureTypes: ["Zip Fly"],
        occasions: ["Casual", "Smart Casual"],
        brands: ["Levi's"],
        materials: ["Cotton Blend"],
        tags: ["Classic", "Denim"],
      },
      {
        name: "Baggy Fit Acid Wash Jeans",
        description:
          "Bold baggy fit jeans with an all-over acid wash effect. Ultra-wide leg and relaxed waist for maximum streetwear credibility.",
        price: 2499,
        originalPrice: 3499,
        image:
          "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=500&q=80",
        category: "jeans",
        unit: "piece",
        stock: 30,
        isOrganic: false,
        rating: 4.1,
        reviewCount: 42,
        sizes: ["30", "32", "34", "36"],
        colors: ["Grey", "Blue"],
        fits: ["Baggy Fit"],
        washes: ["Acid Wash"],
        patterns: ["Washed"],
        rises: ["High Rise"],
        stretches: ["Non-Stretchable"],
        lengths: ["Full Length"],
        closureTypes: ["Button Fly"],
        occasions: ["Streetwear"],
        brands: ["Jack & Jones"],
        materials: ["100% Cotton"],
        tags: ["Streetwear", "Washed", "New"],
      },
      {
        name: "Comfort Fit Navy Jeans",
        description:
          "Everyday comfort-fit jeans in deep navy. Elastic waistband and soft denim blend make these ideal for long wear.",
        price: 1399,
        originalPrice: 1899,
        image:
          "https://images.unsplash.com/photo-1578932750294-f5075e85f44a?w=500&q=80",
        category: "jeans",
        unit: "piece",
        stock: 100,
        isOrganic: false,
        rating: 4.4,
        reviewCount: 112,
        sizes: ["32", "34", "36", "38", "40", "42"],
        colors: ["Navy"],
        fits: ["Comfort Fit"],
        washes: ["Dark Wash"],
        patterns: ["Plain"],
        rises: ["Mid Rise"],
        stretches: ["Stretchable"],
        lengths: ["Full Length"],
        closureTypes: ["Drawstring"],
        occasions: ["Casual", "Travel"],
        brands: ["Flying Machine"],
        materials: ["Denim Blend"],
        tags: ["Classic", "Stretchable"],
      },
      {
        name: "Cropped Ankle Length Jeans",
        description:
          "Modern cropped jeans hitting just above the ankle. Clean look with a tapered silhouette for a sharp finish.",
        price: 1599,
        originalPrice: 2099,
        image:
          "https://images.unsplash.com/photo-1555689502-c4b22d76c56f?w=500&q=80",
        category: "jeans",
        unit: "piece",
        stock: 60,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 78,
        sizes: ["28", "30", "32", "34"],
        colors: ["Blue", "Black"],
        fits: ["Slim Fit"],
        washes: ["Medium Wash"],
        patterns: ["Clean Look"],
        rises: ["Mid Rise"],
        stretches: ["Stretchable"],
        lengths: ["Ankle Length"],
        closureTypes: ["Zip Fly"],
        occasions: ["Casual", "Smart Casual"],
        brands: ["U.S. Polo Assn."],
        materials: ["Stretch Denim"],
        tags: ["Slim", "New"],
      },
      {
        name: "Printed Denim Statement Jeans",
        description:
          "Unique laser-printed denim jeans with abstract motifs. For the fashion-forward individual who loves to stand out.",
        price: 2799,
        originalPrice: 3999,
        image:
          "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=500&q=80",
        category: "jeans",
        unit: "piece",
        stock: 20,
        isOrganic: false,
        rating: 4.0,
        reviewCount: 29,
        sizes: ["28", "30", "32", "34"],
        colors: ["Blue"],
        fits: ["Slim Fit"],
        washes: ["Medium Wash"],
        patterns: ["Printed"],
        rises: ["Mid Rise"],
        stretches: ["Stretchable"],
        lengths: ["Full Length"],
        closureTypes: ["Zip Fly"],
        occasions: ["Party Wear", "Streetwear"],
        brands: ["Killer"],
        materials: ["Stretch Denim"],
        tags: ["Streetwear", "New"],
      },
      {
        name: "Vintage Wash Loose Fit Jeans",
        description:
          "Old-school loose fit jeans with an authentic vintage wash. Heavy-duty construction with reinforced stitching throughout.",
        price: 2099,
        originalPrice: 2799,
        image:
          "https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=500&q=80",
        category: "jeans",
        unit: "piece",
        stock: 45,
        isOrganic: false,
        rating: 4.3,
        reviewCount: 63,
        sizes: ["32", "34", "36", "38", "40"],
        colors: ["Blue", "Grey"],
        fits: ["Loose Fit"],
        washes: ["Vintage Wash"],
        patterns: ["Faded"],
        rises: ["High Rise"],
        stretches: ["Non-Stretchable"],
        lengths: ["Full Length"],
        closureTypes: ["Zip Fly"],
        occasions: ["Casual"],
        brands: ["Wrangler"],
        materials: ["100% Cotton"],
        tags: ["Classic", "Washed"],
      },
      {
        name: "Textured Distressed Carrot Fit Jeans",
        description:
          "Trendy carrot-fit silhouette with subtle textured distressing. Tapered from thigh to ankle for a modern profile.",
        price: 2399,
        originalPrice: 3199,
        image:
          "https://images.unsplash.com/photo-1584370848010-d7fe6bc767ec?w=500&q=80",
        category: "jeans",
        unit: "piece",
        stock: 35,
        isOrganic: false,
        rating: 4.4,
        reviewCount: 47,
        sizes: ["28", "30", "32", "34", "36"],
        colors: ["Blue", "Navy"],
        fits: ["Carrot Fit"],
        washes: ["Medium Wash"],
        patterns: ["Distressed", "Textured"],
        rises: ["Mid Rise"],
        stretches: ["Stretchable"],
        lengths: ["Full Length"],
        closureTypes: ["Zip Fly"],
        occasions: ["Casual", "Streetwear"],
        brands: ["Mufti"],
        materials: ["Stretch Denim"],
        tags: ["Streetwear", "New"],
      },
      {
        name: "Olive Cargo Denim Jeans",
        description:
          "Utility-inspired cargo jeans with side pockets in olive green wash. A fusion of workwear durability and casual style.",
        price: 2299,
        originalPrice: 2999,
        image:
          "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=500&q=80",
        category: "jeans",
        unit: "piece",
        stock: 50,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 91,
        sizes: ["30", "32", "34", "36", "38"],
        colors: ["Olive", "Brown"],
        fits: ["Regular Fit"],
        washes: ["Dark Wash"],
        patterns: ["Plain"],
        rises: ["Mid Rise"],
        stretches: ["Stretchable"],
        lengths: ["Full Length"],
        closureTypes: ["Zip Fly"],
        occasions: ["Casual", "Travel"],
        brands: ["Spykar"],
        materials: ["Denim Blend"],
        tags: ["Denim", "New"],
      },
      {
        name: "High Rise Embroidered Jeans",
        description:
          "High-rise jeans with delicate floral embroidery on the back pockets. A refined touch on classic denim craftsmanship.",
        price: 2599,
        originalPrice: 3499,
        image:
          "https://images.unsplash.com/photo-1592878904946-b3cd8ae243d0?w=500&q=80",
        category: "jeans",
        unit: "piece",
        stock: 25,
        isOrganic: false,
        rating: 4.7,
        reviewCount: 145,
        sizes: ["28", "30", "32", "34"],
        colors: ["Blue"],
        fits: ["Straight Fit"],
        washes: ["Medium Wash"],
        patterns: ["Embroidered"],
        rises: ["High Rise"],
        stretches: ["Stretchable"],
        lengths: ["Full Length"],
        closureTypes: ["Zip Fly"],
        occasions: ["Casual", "Smart Casual"],
        brands: ["Pepe Jeans"],
        materials: ["Stretch Denim"],
        tags: ["New", "Classic"],
      },

      // ─── TROUSERS (36–50) ────────────────────────────────────────────
      {
        name: "Classic Formal Pleated Trousers",
        description:
          "Timeless pleated-front formal trousers in premium wool-blend fabric. Sharp creases and a tailored fit for the modern professional.",
        price: 1999,
        originalPrice: 2699,
        image:
          "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&q=80",
        category: "trousers",
        unit: "piece",
        stock: 90,
        isOrganic: false,
        rating: 4.6,
        reviewCount: 167,
        sizes: ["30", "32", "34", "36", "38"],
        colors: ["Black", "Navy", "Grey"],
        fits: ["Regular Fit"],
        patterns: ["Plain"],
        rises: ["Mid Rise"],
        lengths: ["Full Length"],
        closureTypes: ["Button Closure"],
        pocketStyles: ["Pleated"],
        occasions: ["Formal", "Office Wear"],
        brands: ["Raymond"],
        materials: ["Polyester", "Viscose"],
        tags: ["Formal", "Office Wear"],
      },
      {
        name: "Slim Fit Chino Trousers",
        description:
          "Versatile slim-fit chinos in soft brushed cotton. A wardrobe essential that works for both office and weekend outings.",
        price: 1499,
        originalPrice: 1999,
        image:
          "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500&q=80",
        category: "trousers",
        unit: "piece",
        stock: 130,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 234,
        sizes: ["28", "30", "32", "34", "36", "38"],
        colors: ["Beige", "Olive", "Navy", "Khaki"],
        fits: ["Slim Fit"],
        patterns: ["Plain"],
        rises: ["Mid Rise"],
        lengths: ["Full Length"],
        closureTypes: ["Zip Closure"],
        pocketStyles: ["Flat Front"],
        occasions: ["Casual", "Business Casual"],
        brands: ["Allen Solly"],
        materials: ["Cotton"],
        tags: ["Casual", "Slim Fit", "Cotton"],
      },
      {
        name: "Relaxed Fit Linen Trousers",
        description:
          "Breezy relaxed-fit trousers in 100% linen. The ideal summer pant with a drawstring waist for effortless comfort.",
        price: 1799,
        originalPrice: 2499,
        image:
          "https://images.unsplash.com/photo-1619533394727-57d522857f89?w=500&q=80",
        category: "trousers",
        unit: "piece",
        stock: 65,
        isOrganic: false,
        rating: 4.4,
        reviewCount: 112,
        sizes: ["30", "32", "34", "36", "38"],
        colors: ["White", "Cream", "Beige"],
        fits: ["Relaxed Fit"],
        patterns: ["Plain"],
        rises: ["Mid Rise"],
        lengths: ["Full Length"],
        closureTypes: ["Drawstring"],
        pocketStyles: ["Flat Front"],
        occasions: ["Casual", "Travel"],
        brands: ["Louis Philippe"],
        materials: ["Linen"],
        tags: ["Linen", "Relaxed Fit", "Travel Friendly"],
      },
      {
        name: "Flat Front Formal Trousers",
        description:
          "Clean flat-front formal trousers with a medium crease. Wrinkle-resistant fabric for all-day professional polish.",
        price: 1699,
        originalPrice: 2199,
        image:
          "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&q=80",
        category: "trousers",
        unit: "piece",
        stock: 85,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 156,
        sizes: ["30", "32", "34", "36", "38", "40"],
        colors: ["Black", "Grey", "Navy"],
        fits: ["Regular Fit"],
        patterns: ["Plain"],
        rises: ["Mid Rise"],
        lengths: ["Full Length"],
        closureTypes: ["Button Closure"],
        pocketStyles: ["Flat Front"],
        occasions: ["Formal", "Office Wear"],
        brands: ["Van Heusen"],
        materials: ["Polyester"],
        tags: ["Formal", "Wrinkle Free", "Office Wear"],
      },
      {
        name: "Textured Self-Design Trousers",
        description:
          "Subtly textured self-design trousers for the discerning dresser. The rich fabric elevates any formal ensemble.",
        price: 2299,
        originalPrice: 2999,
        image:
          "https://images.unsplash.com/photo-1610652492500-ded49ceeb51b?w=500&q=80",
        category: "trousers",
        unit: "piece",
        stock: 50,
        isOrganic: false,
        rating: 4.6,
        reviewCount: 89,
        sizes: ["30", "32", "34", "36"],
        colors: ["Grey", "Brown", "Navy"],
        fits: ["Slim Fit"],
        patterns: ["Self Design", "Textured"],
        rises: ["Mid Rise"],
        lengths: ["Full Length"],
        closureTypes: ["Zip Closure"],
        pocketStyles: ["Flat Front"],
        occasions: ["Formal", "Business Casual"],
        brands: ["Blackberrys"],
        materials: ["Polyester", "Viscose"],
        tags: ["Formal", "New Arrivals"],
      },
      {
        name: "Cargo Pocket Casual Trousers",
        description:
          "Utility cargo trousers with multiple pockets and an adjustable hem. Built tough from cotton ripstop fabric.",
        price: 1599,
        originalPrice: 2199,
        image:
          "https://images.unsplash.com/photo-1517438476312-10d79c077509?w=500&q=80",
        category: "trousers",
        unit: "piece",
        stock: 75,
        isOrganic: false,
        rating: 4.3,
        reviewCount: 98,
        sizes: ["30", "32", "34", "36", "38"],
        colors: ["Olive", "Khaki", "Black"],
        fits: ["Relaxed Fit"],
        patterns: ["Plain"],
        rises: ["Mid Rise"],
        lengths: ["Full Length"],
        closureTypes: ["Zip Closure"],
        pocketStyles: ["Cargo"],
        occasions: ["Casual", "Travel"],
        brands: ["Jack & Jones"],
        materials: ["Cotton"],
        tags: ["Casual", "Travel Friendly"],
      },
      {
        name: "Cropped Ankle Slim Trousers",
        description:
          "Modern ankle-length trousers with a sharp slim fit. Perfect for showcasing your footwear while staying stylish.",
        price: 1399,
        originalPrice: 1899,
        image:
          "https://images.unsplash.com/photo-1519750783826-e2420f4d687f?w=500&q=80",
        category: "trousers",
        unit: "piece",
        stock: 60,
        isOrganic: false,
        rating: 4.2,
        reviewCount: 67,
        sizes: ["28", "30", "32", "34", "36"],
        colors: ["Beige", "Grey", "Navy"],
        fits: ["Slim Fit"],
        patterns: ["Plain"],
        rises: ["Mid Rise"],
        lengths: ["Ankle Length"],
        closureTypes: ["Zip Closure"],
        pocketStyles: ["Flat Front"],
        occasions: ["Casual", "Smart Casual"],
        brands: ["U.S. Polo Assn."],
        materials: ["Cotton", "Polyester"],
        tags: ["Slim Fit", "New Arrivals"],
      },
      {
        name: "Elastic Waist Jogger Trousers",
        description:
          "Athleisure jogger trousers with an elasticated waist and cuffed ankles. Soft jersey cotton for workout-to-street versatility.",
        price: 999,
        originalPrice: 1499,
        image:
          "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=500&q=80",
        category: "trousers",
        unit: "piece",
        stock: 120,
        isOrganic: false,
        rating: 4.7,
        reviewCount: 278,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Black", "Grey", "Navy", "Olive"],
        fits: ["Comfort Fit"],
        patterns: ["Plain"],
        rises: ["Mid Rise"],
        lengths: ["Full Length"],
        closureTypes: ["Elastic Waist"],
        pocketStyles: ["Flat Front"],
        occasions: ["Casual"],
        brands: ["Tommy Hilfiger"],
        materials: ["Cotton"],
        tags: ["Casual", "Stretchable"],
      },
      {
        name: "Pinstripe Formal Trousers",
        description:
          "Elegant pinstripe trousers for the boardroom. Fine wool-blend fabric with a tailored regular fit that commands respect.",
        price: 2499,
        originalPrice: 3299,
        image:
          "https://images.unsplash.com/photo-1519244703995-f4e0900fcb29?w=500&q=80",
        category: "trousers",
        unit: "piece",
        stock: 40,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 73,
        sizes: ["30", "32", "34", "36", "38"],
        colors: ["Grey", "Navy", "Black"],
        fits: ["Regular Fit"],
        patterns: ["Stripes"],
        rises: ["Mid Rise"],
        lengths: ["Full Length"],
        closureTypes: ["Button Closure"],
        pocketStyles: ["Pleated"],
        occasions: ["Formal", "Office Wear"],
        brands: ["Raymond"],
        materials: ["Polyester", "Viscose"],
        tags: ["Formal", "Office Wear"],
      },
      {
        name: "Straight Fit Cotton Chinos",
        description:
          "Comfortable straight-fit chinos in soft-washed cotton. An everyday essential that pairs with anything from tees to blazers.",
        price: 1299,
        originalPrice: 1799,
        image:
          "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=500&q=80",
        category: "trousers",
        unit: "piece",
        stock: 110,
        isOrganic: false,
        rating: 4.4,
        reviewCount: 189,
        sizes: ["30", "32", "34", "36", "38", "40"],
        colors: ["Brown", "Beige", "Green", "Cream"],
        fits: ["Straight Fit"],
        patterns: ["Plain"],
        rises: ["Mid Rise"],
        lengths: ["Full Length"],
        closureTypes: ["Zip Closure"],
        pocketStyles: ["Flat Front"],
        occasions: ["Casual", "Smart Casual"],
        brands: ["Peter England"],
        materials: ["Cotton"],
        tags: ["Casual", "Regular Fit", "Cotton"],
      },
      {
        name: "Checked Formal Trousers",
        description:
          "Sophisticated micro-check pattern formal trousers. Tailored fit with side pockets and a polished finish for office elegance.",
        price: 2099,
        originalPrice: 2799,
        image:
          "https://images.unsplash.com/photo-1633966887768-64f9a867bdba?w=500&q=80",
        category: "trousers",
        unit: "piece",
        stock: 55,
        isOrganic: false,
        rating: 4.3,
        reviewCount: 64,
        sizes: ["30", "32", "34", "36"],
        colors: ["Grey", "Beige", "Blue"],
        fits: ["Slim Fit"],
        patterns: ["Checks"],
        rises: ["Mid Rise"],
        lengths: ["Full Length"],
        closureTypes: ["Button Closure"],
        pocketStyles: ["Flat Front"],
        occasions: ["Formal", "Business Casual"],
        brands: ["Allen Solly"],
        materials: ["Polyester", "Cotton"],
        tags: ["Formal", "New Arrivals"],
      },
      {
        name: "High Rise Wide Leg Trousers",
        description:
          "On-trend high-rise wide leg trousers with a flowing silhouette. Lyocell blend fabric drapes beautifully for a luxe look.",
        price: 1899,
        originalPrice: 2599,
        image:
          "https://images.unsplash.com/photo-1551854838-212c50b4c184?w=500&q=80",
        category: "trousers",
        unit: "piece",
        stock: 45,
        isOrganic: false,
        rating: 4.6,
        reviewCount: 102,
        sizes: ["28", "30", "32", "34", "36"],
        colors: ["Black", "Off White", "Maroon"],
        fits: ["Loose Fit"],
        patterns: ["Plain"],
        rises: ["High Rise"],
        lengths: ["Full Length"],
        closureTypes: ["Zip Closure"],
        pocketStyles: ["Flat Front"],
        occasions: ["Party Wear", "Smart Casual"],
        brands: ["Louis Philippe"],
        materials: ["Lyocell"],
        tags: ["New Arrivals"],
      },
      {
        name: "Stretchable Slim Formal Trousers",
        description:
          "Performance stretch formal trousers that move with you. Four-way stretch fabric ensures comfort from desk to dinner.",
        price: 1799,
        originalPrice: 2399,
        image:
          "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=500&q=80",
        category: "trousers",
        unit: "piece",
        stock: 80,
        isOrganic: false,
        rating: 4.5,
        reviewCount: 143,
        sizes: ["30", "32", "34", "36", "38"],
        colors: ["Black", "Navy", "Grey"],
        fits: ["Slim Fit"],
        patterns: ["Plain"],
        rises: ["Mid Rise"],
        lengths: ["Full Length"],
        closureTypes: ["Button Closure"],
        pocketStyles: ["Flat Front"],
        occasions: ["Formal", "Office Wear"],
        brands: ["Blackberrys"],
        materials: ["Polyester", "Nylon"],
        tags: ["Formal", "Stretchable", "Office Wear"],
      },
      {
        name: "Corduroy Baggy Trousers",
        description:
          "Retro-inspired corduroy trousers with a relaxed baggy fit. Rich texture and deep color make these a seasonal statement.",
        price: 1699,
        originalPrice: 2299,
        image:
          "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&q=80",
        category: "trousers",
        unit: "piece",
        stock: 35,
        isOrganic: false,
        rating: 4.2,
        reviewCount: 38,
        sizes: ["30", "32", "34", "36"],
        colors: ["Brown", "Olive", "Maroon"],
        fits: ["Baggy Fit"],
        patterns: ["Textured"],
        rises: ["High Rise"],
        lengths: ["Full Length"],
        closureTypes: ["Zip Closure"],
        pocketStyles: ["Flat Front"],
        occasions: ["Casual"],
        brands: ["Levi's"],
        materials: ["Cotton"],
        tags: ["Casual", "New Arrivals"],
      },
      {
        name: "Wrinkle-Free Travel Trousers",
        description:
          "Engineered wrinkle-free trousers ideal for travel. Lightweight nylon-blend fabric that stays sharp from check-in to check-out.",
        price: 1999,
        originalPrice: 2699,
        image:
          "https://images.unsplash.com/photo-1588361861040-ac9b1018f6d5?w=500&q=80",
        category: "trousers",
        unit: "piece",
        stock: 70,
        isOrganic: false,
        rating: 4.7,
        reviewCount: 198,
        sizes: ["30", "32", "34", "36", "38", "40"],
        colors: ["Black", "Navy", "Khaki"],
        fits: ["Regular Fit"],
        patterns: ["Plain"],
        rises: ["Mid Rise"],
        lengths: ["Full Length"],
        closureTypes: ["Zip Closure"],
        pocketStyles: ["Flat Front"],
        occasions: ["Formal", "Travel"],
        brands: ["Van Heusen"],
        materials: ["Nylon", "Polyester"],
        tags: ["Wrinkle Free", "Travel Friendly", "Formal"],
      },
    ];

    await prisma.product.createMany({ data: products });
    console.log(`Created ${products.length} products....`);

    console.log("Seed completed successfully !!!");
    process.exit(0);
  } catch (error) {
    console.error("Seed error: ", error);
    process.exit(1);
  } finally {
    await prisma.$disconnect;
  }
};

seedDB();
